project:
  title: SIGCSE 2025
  lib-dir: quarto_files
format:
  revealjs: 
    toc: false
    parallax-background-image: images/parallax-1.webp
    parallax-background-size: "3940px 1080px"
    parallax-background-horizontal: 100
    parallax-background-vertical: 0
