svg:
	dot -Tsvg -O merkle.dot
	/bin/mv -f merkle.dot.svg merkle.dot.1.svg
	dot -Tsvg perfect-tree.dot -o perfect-tree.svg

png:
	dot -Tpng -O merkle.dot
	/bin/mv -f merkle.dot.png merkle.dot.1.png
	dot -Tpng perfect-tree.dot -o perfect-tree.png
